### ISSUE TITLE
make a package (and publish on PyPi ?)

### ISSUE THREAD

**Issue by s-celles** [martinohanlon/flightlight#2]
Hello,

you might make a package.

Here is some tutorials
http://python-packaging.readthedocs.org/en/latest/minimal.html
https://pythonhosted.org/an_example_pypi_project/setuptools.html

You could also publish on PyPi.

Even if you don't publish on PyPi your project will be installable using

```
pip install git+https://github.com/martinohanlon/flightlight.git
```

Kind regards

**Comment by martinohanlon** [comment]
I there is sufficient interest I'll make a package, but it doesn't seem likely.
